# Generated by Django 4.1.5 on 2023-01-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.URLField(default='https://www.pngitem.com/pimgs/m/421-4213053_default-avatar-icon-hd-png-download.png'),
        ),
    ]
